#!/usr/bin/env python3
"""extract HP fonts from x50ng snapshots and emit C glyph data."""
import os, sys

HP = "/tmp/eqw_test/hp"

def read_pgm(path):
    with open(path, "rb") as f:
        f.readline()
        line = f.readline()
        while line.startswith(b"#"): line = f.readline()
        w, h = map(int, line.split())
        f.readline()
        return w, h, f.read(w * h)

def find_snap(name):
    for f in os.listdir(HP):
        if f.endswith(f"_{name}.pgm"):
            return os.path.join(HP, f)
    return None

def cols_dark(w, h, data, x0, x1, y0, y1):
    return [any(data[y * w + x] < 0x80 for y in range(y0, y1))
            for x in range(x0, x1)]

def split_spans(cd, x_offset):
    spans = []; in_g = False; sx = None
    for i, c in enumerate(cd):
        if c and not in_g: in_g = True; sx = x_offset + i
        elif not c and in_g: in_g = False; spans.append((sx, x_offset + i))
    return spans

def extract_band(name, y0, y1, expected):
    p = find_snap(name)
    if not p: return {}
    w, h, data = read_pgm(p)
    cd = cols_dark(w, h, data, 0, w, y0, y1)
    spans = split_spans(cd, 0)
    if len(spans) != len(expected): return {}
    out = {}
    for (sx, ex), c in zip(spans, expected):
        rows = []
        for y in range(y0, y1):
            bits = 0
            for x in range(sx, ex):
                if data[y * w + x] < 0x80:
                    bits |= (1 << (x - sx))
            rows.append(bits)
        out[c] = (ex - sx, y1 - y0, rows)
    return out

def detect_band():
    p = find_snap("name_X")
    w, h, data = read_pgm(p)
    miny, maxy = h, -1
    for y in range(0, h - 9):
        for x in range(w):
            if data[y * w + x] < 0x80:
                miny = min(miny, y); maxy = max(maxy, y)
    return (miny, maxy + 1)

y0, y1 = detect_band()
print(f"stack band {y0}..{y1}", file=sys.stderr)

glyphs = {}

def add(c, g):
    if c not in glyphs: glyphs[c] = g

# Solo extractions
solo = []
for d in "0123456789": solo.append((f"num_{d}", d))
for c in "ABCDEFGHIJKLMNOPQRSTUVWYZ": solo.append((f"name_{c}", c))
for c in "abefghjklmnortyz": solo.append((f"name_{c}", c))
solo.append(("name_X", "X"))
solo.append(("name_x", "x"))

for name, c in solo:
    p = find_snap(name)
    if not p: continue
    w, h, data = read_pgm(p)
    minx, maxx = w, -1
    for y in range(y0, y1):
        for x in range(w):
            if data[y * w + x] < 0x80:
                minx = min(minx, x); maxx = max(maxx, x)
    if maxx >= 0:
        rows = []
        for y in range(y0, y1):
            bits = 0
            for x in range(minx, maxx + 1):
                if data[y * w + x] < 0x80:
                    bits |= (1 << (x - minx))
            rows.append(bits)
        add(c, (maxx - minx + 1, y1 - y0, rows))

# Multi-char (band-aligned) snapshots for punctuation
mults = [
    ("num_3p14",       list("3.14")),
    ("add_1_2",        list("1+2")),
    ("sub_5_3",        list("5-3")),
    ("mul_2_3",        ["2", "\xb7", "3"]),  # ·
    ("uf_F_x",         list("F(X)")),
    ("complex_X_Y",    list("(X,Y)")),
    ("where_const_eq", list("5|X=5")),
]
for name, exp in mults:
    res = extract_band(name, y0, y1, exp)
    for c, g in res.items():
        add(c, g)

# Print preview to stderr
for c in sorted(glyphs.keys()):
    gw, gh, rows = glyphs[c]
    print(f"/* '{c}' ({gw}x{gh}) */", file=sys.stderr)
    for r in rows:
        print("  " + "".join("#" if r & (1 << b) else "." for b in range(gw)), file=sys.stderr)

def safe(c):
    nm = {".":"period","+":"plus","-":"minus","*":"star",
          "(":"lparen",")":"rparen","=":"eq",",":"comma",
          "|":"pipe","/":"slash","\xb7":"cdot",
          "^":"caret","[":"lbrack","]":"rbrack"}
    if c in nm: return nm[c]
    if c.isalpha() or c.isdigit(): return c
    return f"u{ord(c):04x}"

# Pad to 7 rows
for c in list(glyphs):
    gw, gh, rows = glyphs[c]
    if gh < 7: rows = rows + [0] * (7 - gh); gh = 7
    elif gh > 7: rows = rows[:7]; gh = 7
    glyphs[c] = (gw, gh, rows)

# Emit C
print('/* hp_font.c — auto-generated by tools/gen_hp_font.py from x50ng */')
print('#include "hp_font.h"')
print()
for c in sorted(glyphs.keys()):
    gw, gh, rows = glyphs[c]
    print(f"static const uint8_t hp_g_{safe(c)}[7] = {{ {', '.join(str(r) for r in rows)} }};")
print()
print('const hp_glyph_t hp_glyph_table[256] = {')
for c in sorted(glyphs.keys()):
    if len(c) != 1: continue
    code = ord(c)
    if code > 127: continue
    gw, gh, rows = glyphs[c]
    advance = gw + 1
    if c == "'": entry = "[39]"
    elif c == "\\": entry = "[92]"
    else: entry = f"['{c}']"
    print(f"  {entry} = {{ {gw}, {advance}, hp_g_{safe(c)} }},")
print('};')
print(f'/* total: {len(glyphs)} glyphs */')
